In [6]:
import requests
import json
import pandas as pd

In [7]:
API_key = "1fd00ba235bf47278e2c13643565a3ce"

In [12]:
#Источник: https://newsapi.org/
#1-й запрос
import requests
url = ('https://newsapi.org/v2/everything?'
       'q=Apple&'
       'apiKey=1fd00ba235bf47278e2c13643565a3ce')
response = requests.get(url)
res = response.json()
res

{'status': 'ok',
 'totalResults': 38194,
 'articles': [{'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Verge Staff',
   'title': 'Rank the 50 best Apple products',
   'description': 'In honor of Apple’s 50th anniversary, The Verge picked 50 of our favorite Apple products, from the OG iPhone to GarageBand. Now you can help us by live ranking them all to choose a winner.',
   'url': 'https://www.theverge.com/cs/tech/900477/apple-50-anniversary-rank-products',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/Rank-Apple-Products-Lead-Art-1.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-27T10:00:00Z',
   'content': "For any one person, ranking 50 items can be a long and tedious process. For a community, however, it's markedly easier. Rather than have each user submit a full list, we can break down the rankings i… [+1027 chars]"},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jason Snell',
   'title': 'Between Jobs',
   'description': "This is part of our package about Apple's 50th anniversary, read more here. It's a famous story on its way to becoming legendary: Apple cofounder Steve Jobs was pushed out of Apple in 1985, spent more than a decade in the wilderness, and then returned to Appl…",
   'url': 'https://www.theverge.com/tech/897520/apple-without-steve-jobs-90s',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/268248_APPLE_50_NO_STEVE_JOBS_CVirginia_0a082a.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-30T17:57:09Z',
   'content': '<ul><li></li><li></li></ul>\r\nWith Steve Jobs in exile, Apples 90s featured some of its most lasting triumphs and weirdest failures.\r\nby\r\nJason SnellClose\r\nPosts from this author will be added to your… [+11858 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Apple could put ads in Maps as soon as this summer',
   'description': "Apple will soon bring advertisements to its Maps app on mobile and the web, according to a report from Bloomberg's Mark Gurman. The ads, which Apple could reportedly announce this month before rolling them out in the summer, could allow businesses to pay for …",
   'url': 'https://www.theverge.com/tech/899053/apple-maps-advertising-rumor',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/chorus/uploads/chorus_asset/file/25479100/STK476_LOCATION_DATA_CVIRGINIA_D.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-23T18:54:44Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe rollout could allow businesses to pay for the top spot on Apple Maps search results.\r\nThe rollout could allow businesses to pay for the top spot on Apple Map… [+2487 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Noam Scheiber',
   'title': 'How the Vision Pro Rollout Inflamed Tensions at Apple',
   'description': 'Even before the headset’s release, the workforce at Apple Stores was under duress. Trying to get customers interested in the Vision Pro made it worse.',
   'url': 'https://www.wired.com/story/book-excerpt-mutiny-noam-scheiber-apple-vision-pro/',
   'urlToImage': 'https://media.wired.com/photos/69cd244228d35b2c1dfa6820/191:100/w_1280,c_limit/excerpt-AppleVisionPro_V2.jpg',
   'publishedAt': '2026-04-07T10:00:00Z',
   'content': 'To roll out its new mixed-reality headset, the Vision Pro, Apple devised a plan almost as intricate as the device itself.\r\nIn January 2024, Apple summoned hundreds of retail employees to its campus i… [+4118 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'John.Higgins',
   'title': 'Apple Studio Display XDR review: pro at a premium',
   'description': "It's been almost exactly four years since Apple released the 5K Studio Display that so many wanted, even if it didn't really deliver as a high-end display. Apple has now revamped the Studio Display lineup, sort of, with another Studio Display and the Studio D…",
   'url': 'https://www.theverge.com/tech/891436/apple-studio-display-xdr-review',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/268390_Apple_Studio_Display_XDR_JHiggins_0005.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-09T19:53:45Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nProfessionals will love the accurate and plentiful reference modes, but far better options exist for the rest of us.\r\nIf you buy something from a Verge link, Vox… [+13122 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jennifer Pattison Tuohy',
   'title': 'Nuki adds Apple Home Key to its smart lock',
   'description': "This week, my top pick for a retrofit smart lock launched the first Aliro-compatible keypad. The Nuki Keypad 2 NFC ($179) brings tap-to-unlock via Apple's Home Key and Samsung's Digital Home Key to the Nuki smart lock, allowing you to tap your phone or smartw…",
   'url': 'https://www.theverge.com/tech/899330/nuki-keypad-2-nfc-aliro-apple-homekey-launch',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/Nuki-Keypad-2-NFC_-convenient-access-with-tap-to-unlock_%C2%A9Nuki.jpg?quality=90&strip=all&crop=0%2C10.737777045019%2C100%2C78.524445909961&w=1200',
   'publishedAt': '2026-03-24T13:02:13Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe Keypad NFC 2 supports Aliro, bringing tap-to-unlock with Apple and Samsungs digital keys to the retrofit lock.\r\nThe Keypad NFC 2 supports Aliro, bringing tap… [+4019 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Victoria Song',
   'title': 'How the Apple Watch defined modern health tech',
   'description': "This is Optimizer, a weekly newsletter sent every Friday from Verge senior reviewer Victoria Song that dissects and discusses the latest gizmos and potions that swear they're going to change your life. Opt in for Optimizer here. You can trace the state of hea…",
   'url': 'https://www.theverge.com/column/906391/apple-watch-optimizer-apple-50-health-tech-wearables',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/04/268248_APPLE_50_APPLE_WATCH_CVirginia.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-04-03T12:52:14Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nDigital health screeners werent a thing until the Apple Watch. Its shaped how we think about wearables ever since.\r\nby\r\nVictoria SongClose\r\nSenior Reviewer, Wear… [+12217 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Andrew Liszewski',
   'title': 'Apple is testing a standalone app for its overhauled Siri',
   'description': 'Apple\'s efforts to rebuild its Apple Intelligence AI platform will make its debut at its Worldwide Developers Conference on June 8th. A new version of Siri that transforms the voice assistant into a "systemwide AI agent with deep integration across applicatio…',
   'url': 'https://www.theverge.com/tech/899801/apple-wwdc-2026-new-siri-apple-intelligence-standalone-app',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/STK071_APPLE_E.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-24T20:41:24Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nA modernized Siri will debut as part of iOS 27 and macOS 27 updates at WWDC 2026, according to a report from Bloomberg.\r\nA modernized Siri will debut as part of … [+3247 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'David Pierce',
   'title': 'Here’s how to rank the 50 best Apple products ever',
   'description': "Apple turns 50 next week, and we're going to spend the week covering the company, its products, its legacy, and its future. But mostly, we're going to spend the week debating which Apple products are the best. And we need your help. Our ranking system is live…",
   'url': 'https://www.theverge.com/podcast/901378/apple-50-anniversary-rank-vergecast',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/VRG_VST_327_Apple_Rank.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-26T23:31:02Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nWe picked the products. Now you can put them in order.\r\nWe picked the products. Now you can put them in order.\r\nby\r\nDavid PierceClose\r\nPosts from this author wil… [+3090 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'David Pierce',
   'title': 'The MacBook Neo is a winner',
   'description': 'It was a little surprising to see Apple decide to leap fully into the affordable laptop market, to try and compete with devices the company typically prefers to just look down its nose at. It was also a little surprising to see Apple basically nail it on the …',
   'url': 'https://www.theverge.com/podcast/894274/macbook-neo-review-xbox-helix-vergecast',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/VRG_VST_0313_Site.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-13T13:13:16Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nOn The Vergecast: Apples newest and next gadgets, the next Xbox is a PC, and the Big Tech space race.\r\nOn The Vergecast: Apples newest and next gadgets, the next… [+3114 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Andrew Liszewski',
   'title': 'Hermès doesn’t include a power adapter with its $5,150 charging case',
   'description': "Over a decade after Apple first partnered with Hermès for a special Apple Watch collaboration, the French luxury goods maker has released a new collection of leather-wrapped charging accessories for Apple's mobile devices. The most expensive option is a multi…",
   'url': 'https://www.theverge.com/tech/897474/hermes-paddock-wireless-charger-apple-watch-airpods-iphone-leather-luxury',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/hermes_case1.jpg?quality=90&strip=all&crop=0%2C10.723165084465%2C100%2C78.55366983107&w=1200',
   'publishedAt': '2026-03-19T19:08:03Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nYou can charge your Apple Watch and iPhone for the cost of three MacBook Pros.\r\nYou can charge your Apple Watch and iPhone for the cost of three MacBook Pros.\r\nb… [+2567 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Sheena Vasani',
   'title': 'The Apple Watch SE 3 is even easier to recommend at $50 off',
   'description': 'When Apple released the latest Apple Watch SE, it surprised us, outshining Apple’s more expensive models while improving on the basics. Now that it’s on sale, it’s even easier to recommend. The LTE-enabled model has dropped back to its all-time low of $249 ($…',
   'url': 'https://www.theverge.com/gadgets/899671/apple-watch-se-third-generation-deal-sale',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/09/257944_Applewatch_SE_AKrales_0070.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-24T17:18:10Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nApples entry-level smartwatch includes many flagship features, from an always-on display to on-device Siri.\r\nApples entry-level smartwatch includes many flagship… [+3259 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Apple’s $549 AirPods Max 2 add better ANC and live translation',
   'description': "Apple has just announced the AirPods Max 2 with better noise cancellation and sound quality. The second generation of Apple's over-ear headphones starts at $549 and comes equipped with an H2 chip, powering features like adaptive audio, conversation awareness,…",
   'url': 'https://www.theverge.com/tech/895155/apple-airpods-max-2-pricing-availability',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/Apple-AirPods-Max-2-color-lineup.jpg?quality=90&strip=all&crop=0%2C3.4613147178592%2C100%2C93.077370564282&w=1200',
   'publishedAt': '2026-03-16T13:33:17Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nThe latest version of Apples over-ear headphones comes packed with features like adaptive audio, conversation awareness, and more.\r\nThe latest version of Apples … [+2543 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Richard Lawler, Jess Weatherbed',
   'title': 'Apple’s WWDC 2026 event starts June 8th',
   'description': "Apple has set a date for this year's Worldwide Developers Conference (WWDC), scheduling the keynote and Platforms State of the Union on June 8th at Apple Park and running through June 12th. As usual, we will be tuned in to find out what's new in the 2027-bran…",
   'url': 'https://www.theverge.com/news/898997/apple-wwdc-2026-june-8-ios-27-ai-siri',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2026/03/Apple-WWDC26-event-branding.jpg?quality=90&strip=all&crop=0%2C3.4613147178592%2C100%2C93.077370564282&w=1200',
   'publishedAt': '2026-03-23T17:21:53Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nWere still waiting to see Siris AI upgrade.\r\nWere still waiting to see Siris AI upgrade.\r\nby\r\nRichard LawlerClose\r\nPosts from this author will be added to your d… [+3262 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Dell Cameron, Louise Matsakis',
   'title': 'Iran Threatens to Start Attacking Major US Tech Firms on April 1',
   'description': 'Tech giants like Apple, Google, and Microsoft are among those on a target list released by Iran’s Islamic Revolutionary Guard Corps.',
   'url': 'https://www.wired.com/story/iran-threatens-to-start-attacking-major-us-tech-firms-on-april-1/',
   'urlToImage': 'https://media.wired.com/photos/69cbf5d389cbdc32deb6bcdf/191:100/w_1280,c_limit/Trump_Iran_Biz_GettyImages-2267975852.jpg',
   'publishedAt': '2026-03-31T21:25:12Z',
   'content': 'Irans Islamic Revolutionary Guard Corps warned Tuesday that it plans to begin attacking more than a dozen American companies across the Middle East on Wednesday in retaliation for the killing of Iran… [+3382 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Jess Weatherbed',
   'title': 'Apple reduces App Store fees in China to ward off regulators',
   'description': 'Apple is cutting App Store developer fees in China from March 15th, dropping its typical commission on purchases from 30 percent down to 25 percent. The decision was made following "discussions with the Chinese regulator," according to Apple\'s announcement, s…',
   'url': 'https://www.theverge.com/tech/894306/apple-app-store-fees-china-reduced-antitrust',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/08/STK071_APPLE_D.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-13T11:16:12Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nCommission rates are dropping from 30 percent to 25 percent.\r\nCommission rates are dropping from 30 percent to 25 percent.\r\nby\r\nJess WeatherbedClose\r\nPosts from … [+2180 chars]'},
  {'source': {'id': 'wired', 'name': 'Wired'},
   'author': 'Ryan Waniata',
   'title': "What's New in the AirPods Max 2? Breaking Down Apple's Headphone Update",
   'description': 'Apple\'s premium over-ears finally have a proper successor, but after five years of waiting, it\'s hard not to wonder: "Is that it?"',
   'url': 'https://www.wired.com/story/apple-airpods-max-2-news/',
   'urlToImage': 'https://media.wired.com/photos/69b851530a629edf8a068be6/191:100/w_1280,c_limit/Apple-AirPods-Max-2-lifestyle.jpg',
   'publishedAt': '2026-03-16T20:14:33Z',
   'content': "Two weeks removed from Apple's latest product event, where we were treated to everything from the new iPhone 17e to the cheapest laptop Apple has ever made, the company surprised us with one more thi… [+2934 chars]"},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Richard Lawler',
   'title': 'Apple smart home display rumors now point to a fall launch with iOS 27',
   'description': 'The rumored "HomePod with a screen" we\'ve heard so much about was reportedly lined up for launch in 2025, and then this spring, and now, according to the latest updates, it\'s on the shelf until this fall. Leaker Kosutami posted as much on X last week, and tod…',
   'url': 'https://www.theverge.com/ai-artificial-intelligence/891723/apple-homepad-delay-rumor',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/11/STKB377_APPLE_HOME_APP_A.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-09T22:26:50Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nApples hardware rollouts will apparently depend on what Siri can do, and when.\r\nApples hardware rollouts will apparently depend on what Siri can do, and when.\r\nb… [+2736 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Mike Pearl',
   'title': 'Apple Removes iPhone Vibe Coding App from App Store',
   'description': 'Vibe coding apps reportedly keep running afoul of an App Store guideline called "Guideline 2.5.2."',
   'url': 'https://gizmodo.com/apple-removes-iphone-vibe-coding-app-from-app-store-2000740084',
   'urlToImage': 'https://gizmodo.com/app/uploads/2020/11/nkfymakb0t5icflu8bxx.jpg',
   'publishedAt': '2026-03-31T09:30:59Z',
   'content': 'The Anything page at the Apple App Store boasted “the fastest way to build apps.” Now what do you see if you visit Anything? That’s right, nothing.\r\nApple removed Anything on Thursday of last week fo… [+2796 chars]'},
  {'source': {'id': None, 'name': 'Gizmodo.com'},
   'author': 'Kyle Barr',
   'title': '8GB of RAM Hasn’t Hurt MacBook Neo Sales at All',
   'description': 'And you can bet Apple is already planning a sequel with slightly more RAM.',
   'url': 'https://gizmodo.com/8gb-of-ram-hasnt-hurt-macbook-neo-sales-at-all-2000743970',
   'urlToImage': 'https://gizmodo.com/app/uploads/2026/03/Apple-Macbook-Neo-March-4th-8-1200x675.jpg',
   'publishedAt': '2026-04-08T14:30:14Z',
   'content': 'The results are in. Customers are coming in hot for Apples $600 MacBook Neo and they don’t seem to care that the laptop has limited memory, given its gateway price into Apples computing ecosystem. No… [+3013 chars]'},
  {'source': {'id': 'the-verge', 'name': 'The Verge'},
   'author': 'Emma Roth',
   'title': 'Apple’s iOS 26.4 update adds age verification in the UK',
   'description': 'Apple now requires users in the UK to verify their age with the launch of iOS 26.4. In a support page on Apple\'s website, the company says users must confirm that they\'re over 18 to "use certain services or features, or take certain actions on their account."…',
   'url': 'https://www.theverge.com/tech/900284/apple-ios-26-4-uk-age-verification',
   'urlToImage': 'https://platform.theverge.com/wp-content/uploads/sites/2/2025/09/257946_iPhone_17_AKrales_0008.jpg?quality=90&strip=all&crop=0%2C10.732984293194%2C100%2C78.534031413613&w=1200',
   'publishedAt': '2026-03-25T13:54:10Z',
   'content': '<ul><li></li><li></li><li></li></ul>\r\nUsers in the UK will be asked to verify that theyre over 18 to use certain services or features.\r\nUsers in the UK will be asked to verify that theyre over 18 to … [+2602 chars]'},

In [88]:
res.keys()

dict_keys(['status', 'totalResults', 'articles'])

In [89]:
res['articles'][0].keys()

dict_keys(['source', 'author', 'title', 'description', 'url', 'urlToImage', 'publishedAt', 'content'])

In [91]:
news_df = pd.DataFrame(res['articles'])
news_df = news_df.drop('urlToImage', axis=1)
news_df.head(10)

,source,author,title,description,url,publishedAt,content
0,"{'id': 'the-verge', 'name': 'The Verge'}",Verge Staff,Rank the 50 best Apple products,"In honor of Apple’s 50th anniversary, The Verg...",https://www.theverge.com/cs/tech/900477/apple-...,2026-03-27T10:00:00Z,"For any one person, ranking 50 items can be a ..."
1,"{'id': 'the-verge', 'name': 'The Verge'}",Jason Snell,Between Jobs,This is part of our package about Apple's 50th...,https://www.theverge.com/tech/897520/apple-wit...,2026-03-30T17:57:09Z,<ul><li></li><li></li></ul>\r\nWith Steve Jobs...
2,"{'id': 'the-verge', 'name': 'The Verge'}",Emma Roth,Apple could put ads in Maps as soon as this su...,Apple will soon bring advertisements to its Ma...,https://www.theverge.com/tech/899053/apple-map...,2026-03-23T18:54:44Z,<ul><li></li><li></li><li></li></ul>\r\nThe ro...
3,"{'id': 'wired', 'name': 'Wired'}",Noam Scheiber,How the Vision Pro Rollout Inflamed Tensions a...,"Even before the headset’s release, the workfor...",https://www.wired.com/story/book-excerpt-mutin...,2026-04-07T10:00:00Z,"To roll out its new mixed-reality headset, the..."
4,"{'id': 'the-verge', 'name': 'The Verge'}",Jennifer Pattison Tuohy,Nuki adds Apple Home Key to its smart lock,"This week, my top pick for a retrofit smart lo...",https://www.theverge.com/tech/899330/nuki-keyp...,2026-03-24T13:02:13Z,<ul><li></li><li></li><li></li></ul>\r\nThe Ke...
5,"{'id': 'the-verge', 'name': 'The Verge'}",John.Higgins,Apple Studio Display XDR review: pro at a premium,It's been almost exactly four years since Appl...,https://www.theverge.com/tech/891436/apple-stu...,2026-03-09T19:53:45Z,<ul><li></li><li></li><li></li></ul>\r\nProfes...
6,"{'id': 'the-verge', 'name': 'The Verge'}",Andrew Liszewski,Apple is testing a standalone app for its over...,Apple's efforts to rebuild its Apple Intellige...,https://www.theverge.com/tech/899801/apple-wwd...,2026-03-24T20:41:24Z,<ul><li></li><li></li><li></li></ul>\r\nA mode...
7,"{'id': 'the-verge', 'name': 'The Verge'}",David Pierce,Here’s how to rank the 50 best Apple products ...,"Apple turns 50 next week, and we're going to s...",https://www.theverge.com/podcast/901378/apple-...,2026-03-26T23:31:02Z,<ul><li></li><li></li><li></li></ul>\r\nWe pic...
8,"{'id': 'the-verge', 'name': 'The Verge'}",Victoria Song,How the Apple Watch defined modern health tech,"This is Optimizer, a weekly newsletter sent ev...",https://www.theverge.com/column/906391/apple-w...,2026-04-03T12:52:14Z,<ul><li></li><li></li><li></li></ul>\r\nDigita...
9,"{'id': 'the-verge', 'name': 'The Verge'}",Sheena Vasani,The Apple Watch SE 3 is even easier to recomme...,"When Apple released the latest Apple Watch SE,...",https://www.theverge.com/gadgets/899671/apple-...,2026-03-24T17:18:10Z,<ul><li></li><li></li><li></li></ul>\r\nApples...

In [92]:
def clean_page_columns(news_df):
    news_df['source'] = news_df['source'].apply(lambda d: d['name'])
    return news_df[['source', 'author', 'title', 'description', 'url', 'publishedAt', 'content']]
page = pd.DataFrame(res['articles'])
news_df_cleaned = clean_page_columns(page)
news_df_cleaned.head(10)

,source,author,title,description,url,publishedAt,content
0,The Verge,Verge Staff,Rank the 50 best Apple products,"In honor of Apple’s 50th anniversary, The Verg...",https://www.theverge.com/cs/tech/900477/apple-...,2026-03-27T10:00:00Z,"For any one person, ranking 50 items can be a ..."
1,The Verge,Jason Snell,Between Jobs,This is part of our package about Apple's 50th...,https://www.theverge.com/tech/897520/apple-wit...,2026-03-30T17:57:09Z,<ul><li></li><li></li></ul>\r\nWith Steve Jobs...
2,The Verge,Emma Roth,Apple could put ads in Maps as soon as this su...,Apple will soon bring advertisements to its Ma...,https://www.theverge.com/tech/899053/apple-map...,2026-03-23T18:54:44Z,<ul><li></li><li></li><li></li></ul>\r\nThe ro...
3,Wired,Noam Scheiber,How the Vision Pro Rollout Inflamed Tensions a...,"Even before the headset’s release, the workfor...",https://www.wired.com/story/book-excerpt-mutin...,2026-04-07T10:00:00Z,"To roll out its new mixed-reality headset, the..."
4,The Verge,Jennifer Pattison Tuohy,Nuki adds Apple Home Key to its smart lock,"This week, my top pick for a retrofit smart lo...",https://www.theverge.com/tech/899330/nuki-keyp...,2026-03-24T13:02:13Z,<ul><li></li><li></li><li></li></ul>\r\nThe Ke...
5,The Verge,John.Higgins,Apple Studio Display XDR review: pro at a premium,It's been almost exactly four years since Appl...,https://www.theverge.com/tech/891436/apple-stu...,2026-03-09T19:53:45Z,<ul><li></li><li></li><li></li></ul>\r\nProfes...
6,The Verge,Andrew Liszewski,Apple is testing a standalone app for its over...,Apple's efforts to rebuild its Apple Intellige...,https://www.theverge.com/tech/899801/apple-wwd...,2026-03-24T20:41:24Z,<ul><li></li><li></li><li></li></ul>\r\nA mode...
7,The Verge,David Pierce,Here’s how to rank the 50 best Apple products ...,"Apple turns 50 next week, and we're going to s...",https://www.theverge.com/podcast/901378/apple-...,2026-03-26T23:31:02Z,<ul><li></li><li></li><li></li></ul>\r\nWe pic...
8,The Verge,Victoria Song,How the Apple Watch defined modern health tech,"This is Optimizer, a weekly newsletter sent ev...",https://www.theverge.com/column/906391/apple-w...,2026-04-03T12:52:14Z,<ul><li></li><li></li><li></li></ul>\r\nDigita...
9,The Verge,Sheena Vasani,The Apple Watch SE 3 is even easier to recomme...,"When Apple released the latest Apple Watch SE,...",https://www.theverge.com/gadgets/899671/apple-...,2026-03-24T17:18:10Z,<ul><li></li><li></li><li></li></ul>\r\nApples...

In [45]:
#2-й запрос
import requests
url = ('https://newsapi.org/v2/top-headlines?'
       'category=business&'
       'apiKey=1fd00ba235bf47278e2c13643565a3ce')
response = requests.get(url)
res = response.json()
news_df = pd.DataFrame(res['articles'])
news_df = news_df.drop('urlToImage', axis=1)
def clean_page_columns(news_df):
    news_df['source'] = news_df['source'].apply(lambda d: d['name'])
    return news_df[['source', 'author', 'title', 'description', 'url', 'publishedAt', 'content']]
page = pd.DataFrame(res['articles'])
news_df_cleaned = clean_page_columns(page)
news_df_cleaned.head(100)

,source,author,title,description,url,publishedAt,content
0,The Wall Street Journal,WSJ,Stock Market Today: Dow Slides; Oil Rebounds A...,None,https://www.wsj.com/livecoverage/stock-market-...,2026-04-09T14:06:00Z,None
1,CNBC,Jeff Cox,"Core inflation was 3% in February, as expected...",The gauge released Thursday offers the Federal...,https://www.cnbc.com/2026/04/09/core-inflation...,2026-04-09T12:35:14Z,Core inflation held above the Federal Reserve'...
2,Bea.gov,None,"GDP (Third Estimate), Industries, Corporate Pr...",Real gross domestic product (GDP) increased at...,https://www.bea.gov/news/2026/gdp-third-estima...,2026-04-09T12:30:00Z,Real gross domestic product (GDP) increased at...
3,Tipranks.com,William White,CoreWeave Stock (CRWV) Soars on a Massive $21B...,CoreWeave stock gained on Thursday after the A...,https://www.tipranks.com/news/coreweave-stock-...,2026-04-09T12:03:38Z,Story Highlights<ul><li>CoreWeave stock rallie...
4,Associated Press,Stan Choe,Oil prices jump back up near $100 a barrel on ...,Oil prices are climbing back toward $100 per b...,https://apnews.com/article/stock-markets-trump...,2026-04-09T12:00:00Z,NEW YORK (AP) Oil prices are climbing back tow...
5,CNBC,Hayley Cuccinello,Family offices piled into oil after capital dr...,After ESG pressures forced private equity inve...,https://www.cnbc.com/2026/04/09/family-offices...,2026-04-09T11:45:10Z,A version of this article first appeared in CN...
6,CNBC,Kai Nicol-Schwarz,OpenAI halts UK stargate project amid regulato...,The major AI infrastructure was announced in S...,https://www.cnbc.com/2026/04/09/openai-halts-u...,2026-04-09T11:06:28Z,OpenAI's Stargate project in the U.K. is being...
7,Aboutamazon.com,"Andy Jassy, CEO of Amazon",CEO Andy Jassy’s 2025 Letter to Shareholders -...,Read Amazon CEO Andy Jassy’s 2025 Letter to Sh...,https://www.aboutamazon.com/news/company-news/...,2026-04-09T10:07:13Z,None
8,Fortune,Nick Lichtenberg,White-collar workers are quietly rebelling aga...,"""AI didn't deliver,"" Johns Hopkins professor S...",https://fortune.com/2026/04/09/ai-backlash-qui...,2026-04-09T10:00:00Z,"There was a moment, not long ago, when shadow ..."
9,Axios,Sam Sabin,Scoop: OpenAI plans staggered rollout of new m...,Model-makers are now so worried about the havo...,https://www.axios.com/2026/04/09/openai-new-mo...,2026-04-09T09:25:36Z,OpenAI is finalizing a model with advanced cyb...
10,Business Insider,"Lucia Moses, Dan Whateley",TikTok's top star teased a $975 million deal a...,Khaby Lame's deal to go public has hit a snag ...,https://www.businessinsider.com/tiktok-creator...,2026-04-09T09:05:00Z,Khaby Lame's mysterious $975 million deal has ...
11,NPR,,Why high oil prices are good for oil companies...,"Yes, higher crude oil prices mean a multibilli...",https://www.npr.org/2026/04/09/nx-s1-5745144/o...,2026-04-09T09:00:00Z,Higher prices are good news for the oil indust...
12,Axios,Courtenay Brown,Fed minutes show willingness to consider inter...,Even as many officials see rate cuts down the ...,https://www.axios.com/2026/04/08/fed-interest-...,2026-04-09T08:31:38Z,Some Federal Reserve officials wanted to keep ...
13,Axios,Avery Lotz,Gen Z's fading AI hype - Axios,Even Zoomers who use AI daily are less excited...,https://www.axios.com/2026/04/09/ai-gen-z-poll...,2026-04-09T04:16:43Z,By the numbers: The share of Gen Z respondents...
14,Associated Press,Jessica Hill,States are struggling to meet their clean ener...,Nevada's largest utility company says it may n...,https://apnews.com/article/ai-data-centers-nev...,2026-04-09T04:08:00Z,LAS VEGAS (AP) Nevadas largest utility says it...
15,Financial Times,"Amelia Pollard, Antoine Gara, Costas Mourselas",Bill Ackman in talks to launch fund to bet on ...,Strategy would echo doomsday trades that earne...,https://www.ft.com/content/70ddffb8-7fdc-437f-...,2026-04-09T04:00:26Z,Then $75 per month. Complete digital access to...
16,Deadline,Dade Hayes,"Paramount Unlikely To Replace Jeff Shell, Insi...",Jeff Shell is unlikely to be directly replaced...,http://deadline.com/2026/04/paramount-jeff-she...,2026-04-09T00:33:00Z,Jeff Shell is unlikely to be directly replaced...
17,Business Insider,Grace Kay,XAI Reorganizes Its Engineering Team Ahead of ...,"A SpaceX executive said xAI is ""clearly behind...",https://www.businessinsider.com/elon-musk-reor...,2026-04-08T22:58:00Z,As Elon Musk's xAI merges more closely with Sp...

In [30]:
#3-й запрос
import requests
url = ('https://newsapi.org/v2/top-headlines?'
       'country=us&'
       'category=business&'
       'apiKey=1fd00ba235bf47278e2c13643565a3ce')
response = requests.get(url)
res = response.json()
news_df = pd.DataFrame(res['articles'])
news_df = news_df.drop('urlToImage', axis=1)
def clean_page_columns(news_df):
    news_df['source'] = news_df['source'].apply(lambda d: d['name'])
    return news_df[['source', 'author', 'title', 'description', 'url', 'publishedAt', 'content']]
page = pd.DataFrame(res['articles'])
news_df_cleaned = clean_page_columns(page)
news_df_cleaned.head(10)

,source,author,title,description,url,publishedAt,content
0,The Wall Street Journal,WSJ,Stock Market Today: Dow Slides; Oil Rebounds A...,None,https://www.wsj.com/livecoverage/stock-market-...,2026-04-09T14:06:00Z,None
1,CNBC,Jeff Cox,"Core inflation was 3% in February, as expected...",The gauge released Thursday offers the Federal...,https://www.cnbc.com/2026/04/09/core-inflation...,2026-04-09T12:35:14Z,Core inflation held above the Federal Reserve'...
2,Bea.gov,None,"GDP (Third Estimate), Industries, Corporate Pr...",Real gross domestic product (GDP) increased at...,https://www.bea.gov/news/2026/gdp-third-estima...,2026-04-09T12:30:00Z,Real gross domestic product (GDP) increased at...
3,Tipranks.com,William White,CoreWeave Stock (CRWV) Soars on a Massive $21B...,CoreWeave stock gained on Thursday after the A...,https://www.tipranks.com/news/coreweave-stock-...,2026-04-09T12:03:38Z,Story Highlights<ul><li>CoreWeave stock rallie...
4,Associated Press,Stan Choe,Oil prices jump back up near $100 a barrel on ...,Oil prices are climbing back toward $100 per b...,https://apnews.com/article/stock-markets-trump...,2026-04-09T12:00:00Z,NEW YORK (AP) Oil prices are climbing back tow...
5,CNBC,Hayley Cuccinello,Family offices piled into oil after capital dr...,After ESG pressures forced private equity inve...,https://www.cnbc.com/2026/04/09/family-offices...,2026-04-09T11:45:10Z,A version of this article first appeared in CN...
6,CNBC,Kai Nicol-Schwarz,OpenAI halts UK stargate project amid regulato...,The major AI infrastructure was announced in S...,https://www.cnbc.com/2026/04/09/openai-halts-u...,2026-04-09T11:06:28Z,OpenAI's Stargate project in the U.K. is being...
7,Aboutamazon.com,"Andy Jassy, CEO of Amazon",CEO Andy Jassy’s 2025 Letter to Shareholders -...,Read Amazon CEO Andy Jassy’s 2025 Letter to Sh...,https://www.aboutamazon.com/news/company-news/...,2026-04-09T10:07:13Z,None
8,Fortune,Nick Lichtenberg,White-collar workers are quietly rebelling aga...,"""AI didn't deliver,"" Johns Hopkins professor S...",https://fortune.com/2026/04/09/ai-backlash-qui...,2026-04-09T10:00:00Z,"There was a moment, not long ago, when shadow ..."
9,Axios,Sam Sabin,Scoop: OpenAI plans staggered rollout of new m...,Model-makers are now so worried about the havo...,https://www.axios.com/2026/04/09/openai-new-mo...,2026-04-09T09:25:36Z,OpenAI is finalizing a model with advanced cyb...

In [40]:
#4-й запрос
import requests
url = ('https://newsapi.org/v2/everything?'
       'q=bitcoin&'
       'sortBy=popularity&'
       'apiKey=1fd00ba235bf47278e2c13643565a3ce')
response = requests.get(url)
res = response.json()
news_df = pd.DataFrame(res['articles'])
news_df = news_df.drop('urlToImage', axis=1)
def clean_page_columns(news_df):
    news_df['source'] = news_df['source'].apply(lambda d: d['name'])
    return news_df[['source', 'author', 'title', 'description', 'url', 'publishedAt', 'content']]
page = pd.DataFrame(res['articles'])
news_df_cleaned = clean_page_columns(page)
news_df_cleaned.head(100)

,source,author,title,description,url,publishedAt,content
0,Wired,Kate Knibbs,Wall Street Is Already Betting on Prediction M...,As the legal war over how to regulate predicti...,https://www.wired.com/story/prediction-markets...,2026-03-16T09:30:00Z,When Troy Dixon first suggested incorporating ...
1,Wired,Matthew S. Smith,Identity Theft Protection Services: Do You Act...,Here's the best advice I have for protecting y...,https://www.wired.com/story/best-id-protection...,2026-03-14T10:30:00Z,Odds are good youve encountered an identity th...
2,Gizmodo.com,Kyle Torpey,UK Man Accuses Spouse of Stealing $172 Million...,"Code is law, some say. That doesn't mean norma...",https://gizmodo.com/uk-man-accuses-spouse-of-s...,2026-03-17T22:47:01Z,"Ping Fai Yuen, who is a U.K. resident, has acc..."
3,Gizmodo.com,Bruce Gil,The New York Times Claims It Finally Unmasked ...,"If true, the man would be one of the richest p...",https://gizmodo.com/the-new-york-times-claims-...,2026-04-08T16:40:08Z,"The real identity of Satoshi Nakamoto, the cre..."
4,Gizmodo.com,Kyle Torpey,"Gemini, Crypto.com Latest Crypto Firms to Blam...","Meanwhile, some companies have abandoned crypt...",https://gizmodo.com/gemini-crypto-com-latest-c...,2026-03-21T17:00:54Z,With the bitcoin price still sitting roughly 4...
...,...,...,...,...,...,...,...
95,Techmeme.com,None,Fannie Mae will accept crypto-backed mortgages...,Wall Street Journal:\nFannie Mae will accept c...,https://www.techmeme.com/260326/p35,2026-03-26T18:40:00Z,About This Page\r\nThis is a Techmeme archive ...
96,Techmeme.com,None,A look at Coinbase One and other insurance-lik...,Bloomberg:\nA look at Coinbase One and other i...,https://www.techmeme.com/260329/p8,2026-03-29T19:40:14Z,About This Page\r\nThis is a Techmeme archive ...
97,Les Numériques,Mathilde DOUSSET,Acheter du Bitcoin quand son prix baisse : opp...,Le Bitcoin est connu pour sa volatilité. En qu...,https://www.lesnumeriques.com/societe-numeriqu...,2026-04-07T07:00:00Z,Le Bitcoin est connu pour sa volatilité. En qu...
98,Les Numériques,Juliette Sbranna,Actualité : X Money : la néobanque d’Elon Musk...,"Elon Musk prépare le lancement de X Money, sa ...",https://www.lesnumeriques.com/societe-numeriqu...,2026-03-11T19:45:00Z,Elon Musk lance sa neobanque ; X Money\r\n© Sh...
99,Internet,info@thehackernews.com (The Hacker News),"⚡ Weekly Recap: Axios Hack, Chrome 0-Day, Fort...",This week had real hits. The key software got ...,https://thehackernews.com/2026/04/weekly-recap...,2026-04-06T12:46:00Z,This week had real hits. The key software got ...

In [42]:
#5-й запрос
import requests
url = ('https://newsapi.org/v2/everything?'
       'q=finance&'
       'sortBy=popularity&'
       'apiKey=1fd00ba235bf47278e2c13643565a3ce')
response = requests.get(url)
res = response.json()
news_df = pd.DataFrame(res['articles'])
news_df = news_df.drop('urlToImage', axis=1)
def clean_page_columns(news_df):
    news_df['source'] = news_df['source'].apply(lambda d: d['name'])
    return news_df[['source', 'author', 'title', 'description', 'url', 'publishedAt', 'content']]
page = pd.DataFrame(res['articles'])
news_df_cleaned = clean_page_columns(page)
news_df_cleaned.head(100)

,source,author,title,description,url,publishedAt,content
0,Wired,Kate Knibbs,Wall Street Is Already Betting on Prediction M...,As the legal war over how to regulate predicti...,https://www.wired.com/story/prediction-markets...,2026-03-16T09:30:00Z,When Troy Dixon first suggested incorporating ...
1,The Verge,Terrence O’Brien,AI Czar David Sacks wants Trump to ‘get out’ o...,"David Sacks, the White House's AI and crypto c...",https://www.theverge.com/policy/895059/trump-a...,2026-03-15T14:13:25Z,<ul><li></li><li></li><li></li></ul>\r\nIt mig...
2,The Verge,Elizabeth Lopatto,"Oh, you think the government will regulate Kal...",The Commodity Futures Trading Commission has a...,https://www.theverge.com/business/896517/kalsh...,2026-03-18T14:20:24Z,"<ul><li></li><li></li><li></li></ul>\r\nOh, yo..."
3,The Verge,Josh Dzieza,You Could Be Next,The LinkedIn post seemed like yet another scam...,https://www.theverge.com/cs/features/877388/wh...,2026-03-10T09:00:01Z,The LinkedIn post seemed like yet another scam...
4,BBC News,Ben Ramsdale,Survival or FA Cup glory - which would you cho...,Leeds visit West Ham on Sunday in the FA Cup q...,https://www.bbc.com/sport/football/articles/c1...,2026-04-05T05:25:09Z,The winner of this year's men's FA Cup will po...
...,...,...,...,...,...,...,...
94,Xataka.com,Javier Marquez,Yuanjie es la desconocida empresa china de tec...,Yuanjie Semiconductor Technology probablemente...,https://www.xataka.com/empresas-y-economia/yua...,2026-03-23T22:00:54Z,Yuanjie Semiconductor Technology probablemente...
95,Themarginalian.org,Maria Popova,Create Dangerously: Albert Camus on the Power ...,"""To create today is to create dangerously... T...",https://www.themarginalian.org/2026/03/24/albe...,2026-03-24T14:29:33Z,“Those who tell you Do not put too much politi...
96,Abcnews.com,Max Zahn,"Stocks close higher, reversing sharp losses af...",Oil prices spiked as high as nearly $120 per b...,https://abcnews.com/Business/stocks-tumble-oil...,2026-03-09T20:21:36Z,"Stocks closed higher on Monday, recovering fro..."
97,Abcnews.com,Arthur Jones II,Treasury taking over federal student loans ami...,The Trump administration is expected to send t...,https://abcnews.com/Politics/treasury-taking-f...,2026-03-19T23:13:39Z,The Trump administration is expected to send t...
98,Abcnews.com,"Gaby Vinick, Will Steakin","With no Musk, voters see 'less intense and noi...",Wisconsin voters will elect another Supreme Co...,https://abcnews.com/Politics/musk-time-voters-...,2026-03-31T09:03:22Z,"Last spring, the Wisconsin Supreme Court race ..."

In [50]:
#6-й запрос
import requests
url = ('https://newsapi.org/v2/everything?'
       'q=акции&'
       'language=ru&'
       'sortBy=popularity&'
       'apiKey=1fd00ba235bf47278e2c13643565a3ce')
response = requests.get(url)
res = response.json()
news_df = pd.DataFrame(res['articles'])
news_df = news_df.drop('urlToImage', axis=1)
def clean_page_columns(news_df):
    news_df['source'] = news_df['source'].apply(lambda d: d['name'])
    return news_df[['source', 'author', 'title', 'description', 'url', 'publishedAt', 'content']]
page = pd.DataFrame(res['articles'])
news_df_cleaned = clean_page_columns(page)
news_df_cleaned.head(100)

,source,author,title,description,url,publishedAt,content
0,Habr.com,klimensky (FirstVDS),"Как Apple едва не уничтожила себя, разрешив кл...",В 1997 году акции Apple стоили 4 доллара. Комп...,https://habr.com/ru/companies/first/articles/1...,2026-03-20T09:40:54Z,"Apple : . , , .\r\n 1994 Apple . Mac «» .\r\n ..."
1,Lifehacker.ru,Мила Цимбал,«Великая китайская распродажа» на AliExpress: ...,"Изучили ассортимент и собрали товары, на котор...",https://lifehacker.ru/vkr-mart-2026/,2026-03-13T11:00:00Z,": 16 «» AliExpress. , , , , 90%. , : .\r\n , -..."
2,Lenta,Кирилл Луцюк,Война с Ираном обрушила акции европейских комп...,Ближневосточный кризис нанес еще один удар по ...,https://lenta.ru/news/2026/04/07/voyna-s-irano...,2026-04-07T12:36:19Z,". Bloomberg.\r\n, Euro Stoxx 50, 50 12 , . S&a..."
3,Lenta,Лилиана Набиуллина,Акции Сбера ускорили рост после слов Грефа о п...,Акции Сбера отреагировали ростом на заявление ...,https://lenta.ru/news/2026/03/17/aktsii-sbera-...,2026-03-17T13:00:52Z,"«» , . 15:10 0,82 , 318,98 , Investing.com.\r\..."
4,Lenta,Алена Шевченко,Россиянам развеяли два популярных мифа об орга...,Качественное органическое вино не имеет дрожже...,https://lenta.ru/news/2026/04/05/rossiyanam-ra...,2026-04-05T04:30:54Z,", , . «.» « ».\r\n , . , , , , , .\r\n« , , ...."
...,...,...,...,...,...,...,...
95,BBC News,https://www.facebook.com/bbcnews,В США проходят акции протеста против Дональда ...,В городах по всей территории США проходят масш...,https://www.bbc.com/russian/articles/cde5lpde4pko,2026-03-29T07:16:19Z,", : « »\r\n« ». , . \r\n , , , , .\r\n« . , , ..."
96,BBC News,None,Как война в Иране бьет по рейтингам Трампа?,"В этом выпуске поговорим о том, как война в Ир...",https://www.bbc.com/russian/podcasts/p076qqzl/...,2026-03-31T00:00:00Z,", . . « !». , .\r\n .\r\n00:00 . \r\n00:44 ?\r..."
97,BBC News,None,Митинги в защиту «Телеграма»: протест или пров...,На 29 марта в России анонсированы протесты про...,https://www.bbc.com/russian/podcasts/p076qqzl/...,2026-03-26T14:33:00Z,"29 . , . , . 1 «». ? ? «» ? -- .\r\n00:00 . \r..."
98,Interfax.ru,None,Суд присудил Газпрому акции ликвидированных юр...,"Интерфакс: ""Газпром"" в суде оформил собственно...",https://www.interfax.ru/business/1078081,2026-03-16T04:12:00Z,". 16 . INTERFAX.RU - """" 342 . - . , 2024-2025 ..."
99,Interfax.ru,None,Производитель игрушек Labubu в 2025 году нарас...,"Интерфакс: Акции компании падают на 21,5% на ф...",https://www.interfax.ru/business/1079854,2026-03-25T07:29:00Z,"21,5% \r\n. 25 . INTERFAX.RU - Pop Mart Intern..."